name: Reusable Deploy
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-slim
        steps:
        - name: Output information
          run: |
            echo "Deploying..."
            echo "${{ toJSON(github) }}"